image: continuumio/miniconda3:latest

stages:
- lib
- tests

variables:
  PROPAGATION_ENVIRONMENT_FILE: env/propagation.yml
  PROPAGATION_ENVIRONMENT_NAME: propagation

install_lib:
  stage: lib
  tags:
    - docker
  script:
  - apt-get install -y libcairo2-dev libjpeg-dev libgif-dev build-essential

main_test:
  stage: tests
  script:
    - echo "Start tests"
    - make test
