image: forum/propagation

stages:
- build
- tests

variables:
  PROPAGATION_ENVIRONMENT_FILE: env/propagation.yml
  PROPAGATION_ENVIRONMENT_NAME: propagation

docker_env:
  stage: build
  tags:
    - bash
  script:
  - echo "==================================";
  - echo "[info] run 'docker build image' ";
  - docker build -t forum/propagation .

functional_tests:
  stage: tests
  tags:
    - docker
  script:
    - echo "==================================";
    - echo "[info] run tests from Makefile ";
    - make test