image: continuumio/miniconda3:latest

stages:
- build

variables:
  PROPAGATION_ENVIRONMENT_FILE: env/propagation.yml
  PROPAGATION_ENVIRONMENT_NAME: propagation

build_env_prop:
  before_script:
    apt-get install -y libcairo2-dev libjpeg-dev libgif-dev build-essential
  stage: build
  tags:
    - docker
  script:
  - make environment_create