image: continuumio/miniconda3:latest

stages:
- lib

variables:
  PROPAGATION_ENVIRONMENT_FILE: env/propagation.yml
  PROPAGATION_ENVIRONMENT_NAME: propagation

install_lib:
  stage: lib
  tags:
    - docker
  script:
  - make test