image: continuumio/miniconda3:latest

stages:
- tests

variables:
  PROPAGATION_ENVIRONMENT_FILE: env/propagation.yml
  PROPAGATION_ENVIRONMENT_NAME: propagation

main_test:
  stage: tests
  tags:
    - docker
  script:
    - make test
