image: continuumio/miniconda3:latest

stages:
- build

variables:
  PROPAGATION_ENVIRONMENT_FILE: propagation/env/propagation.yml
  PROPAGATION_ENVIRONMENT_NAME: propagation

build_env_prop:
  stage: build
  tags:
    - docker
  script:
  - apt-get install -y pkg-config libcairo2-dev
  - conda env create --force --file $PROPAGATION_ENVIRONMENT_FILE
  - source activate propagation